if(NOT DEFINED BIN_DIR OR NOT DEFINED DIST_DIR OR NOT DEFINED EXE)
    message(FATAL_ERROR "dist.cmake needs BIN_DIR, DIST_DIR and EXE")
endif()

file(REMOVE_RECURSE "${DIST_DIR}")
file(MAKE_DIRECTORY "${DIST_DIR}")
file(COPY "${BIN_DIR}/${EXE}" DESTINATION "${DIST_DIR}")
file(GLOB runtime "${BIN_DIR}/*.dll")
foreach(dll IN LISTS runtime)
    file(COPY "${dll}" DESTINATION "${DIST_DIR}")
endforeach()
if(EXISTS "${BIN_DIR}/steam_appid.txt")
    file(COPY "${BIN_DIR}/steam_appid.txt" DESTINATION "${DIST_DIR}")
endif()
file(MAKE_DIRECTORY "${DIST_DIR}/tapes")
file(GLOB shipped "${DIST_DIR}/*")
list(LENGTH shipped count)
message(STATUS "dist: ${count} entries in ${DIST_DIR}")
