"""Emit src/terminal/content/*.inc from the reference assets/disks tree.

One-shot migration. Run from either repo root:

    py tools/export_disks.py ../Anomalous/assets/disks src/terminal/content
"""

import os
import sys

DISKS = [
    ("internal", "kInternalImage", "internal"),
    ("master", "kMasterImage", "master"),
    ("fieldnotes", "kFieldNotesImage", "fieldnotes"),
    ("scratch", "kScratchImage", "scratch"),
    ("rescue", "kRescueImage", "rescue"),
    ("arcade", "kArcadeImage", "arcade"),
]


def read_cfg(path):
    label, capacity = "NO LABEL", 368640
    try:
        with open(path, "r", encoding="utf-8") as handle:
            for line in handle:
                if "=" not in line or line.lstrip().startswith("#"):
                    continue
                key, value = line.split("=", 1)
                key, value = key.strip(), value.strip()
                if key == "label":
                    label = value
                elif key == "capacity":
                    capacity = int(value)
    except FileNotFoundError:
        pass
    return label, capacity


def read_text(path):
    with open(path, "rb") as handle:
        return handle.read().decode("utf-8", "replace").replace("\r\n", "\n")


def parse_exe(text):
    prog, size, infected, run = "none", 16384, 0, None
    for line in text.splitlines():
        if "=" not in line:
            continue
        key, value = line.split("=", 1)
        key, value = key.strip(), value.strip()
        if key == "prog":
            prog = value
        elif key == "size":
            size = int(value)
        elif key == "infected":
            infected = int(value)
        elif key == "text":
            run = value
    return prog, size, infected, run


def raw_literal(text, tag):
    while f'){tag}"' in text:
        tag += "X"
    return f'R"{tag}({text}){tag}"', tag


def emit_file(out, name, path, prefix, index):
    upper = name.upper()
    if upper.endswith(".EXE"):
        prog, size, infected, run = parse_exe(read_text(path))
        run_literal = "{}"
        if run is not None:
            literal, _ = raw_literal(run, "RUN")
            run_literal = literal
        out.append(
            f'    {{"{upper}", {{}}, {run_literal}, FsExe::{prog.capitalize()}, '
            f"{size}, {'true' if infected else 'false'}}},"
        )
        return

    text = read_text(path)
    literal, _ = raw_literal(text, f"{prefix}{index}")
    out.append(f'    {{"{upper}", {literal}, {{}}, FsExe::None, 0, false}},')


def export(src_root, dst_root):
    os.makedirs(dst_root, exist_ok=True)
    for folder, symbol, prefix in DISKS:
        disk_dir = os.path.join(src_root, folder)
        if not os.path.isdir(disk_dir):
            print(f"skip {folder}: no such directory")
            continue

        label, capacity = read_cfg(os.path.join(disk_dir, "disk.cfg"))
        files, dirs = [], []
        index = 0

        for entry in sorted(os.listdir(disk_dir)):
            path = os.path.join(disk_dir, entry)
            if entry == "disk.cfg":
                continue
            if os.path.isdir(path):
                sub = []
                for child in sorted(os.listdir(path)):
                    emit_file(sub, child, os.path.join(path, child), prefix, index)
                    index += 1
                dirs.append((entry.upper(), sub))
                continue
            emit_file(files, entry, path, prefix, index)
            index += 1

        lines = ["// generated by tools/export_disks.py -- do not edit", ""]
        if files:
            lines.append(f"constexpr RomFile {symbol}Files[] = {{")
            lines += files
            lines.append("};")
            lines.append("")

        for dir_name, sub in dirs:
            sym = f"{symbol}{dir_name.capitalize()}"
            lines.append(f"constexpr RomFile {sym}Files[] = {{")
            lines += sub or ["    // (empty)"]
            lines.append("};")
            lines.append("")

        if dirs:
            lines.append(f"constexpr RomDir {symbol}Dirs[] = {{")
            for dir_name, _ in dirs:
                sym = f"{symbol}{dir_name.capitalize()}"
                lines.append(f'    {{"{dir_name}", {sym}Files}},')
            lines.append("};")
            lines.append("")

        files_span = f"{symbol}Files" if files else "{}"
        dirs_span = f"{symbol}Dirs" if dirs else "{}"
        lines.append(
            f'constexpr DiskImage {symbol}{{"{folder}", "{label}", {capacity}, '
            f"{files_span}, {dirs_span}}};"
        )
        lines.append("")

        out_path = os.path.join(dst_root, f"disk_{folder}.inc")
        with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
            handle.write("\n".join(lines))
        print(f"wrote {out_path} ({len(files)} files, {len(dirs)} dirs)")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(__doc__)
        raise SystemExit(1)
    export(sys.argv[1], sys.argv[2])
