import math
import os
import struct
import zlib

ZONES = os.path.join(os.path.dirname(__file__), "..", "assets", "zones")
HEIGHTMAP_SIZE = 129
CELL_SIZE = 2.0
MASK_SIZE = 256
BENCH_TOP = 0.9

CONCRETE = (0.42, 0.41, 0.40)
DARK = (0.30, 0.30, 0.32)
WOOD = (0.36, 0.24, 0.13)
STEEL = (0.55, 0.50, 0.42)


def png_chunk(tag, data):
    chunk = tag + data
    return struct.pack(">I", len(data)) + chunk + struct.pack(">I", zlib.crc32(chunk))


def write_png(path, size, bit_depth, rows):
    ihdr = struct.pack(">IIBBBBB", size, size, bit_depth, 0, 0, 0, 0)
    blob = (b"\x89PNG\r\n\x1a\n" + png_chunk(b"IHDR", ihdr) + png_chunk(b"IDAT", zlib.compress(rows, 9))
            + png_chunk(b"IEND", b""))
    with open(path, "wb") as f:
        f.write(blob)


def write_flat_heightmap(path):
    rows = bytearray()
    for _ in range(HEIGHTMAP_SIZE):
        rows.append(0)
        rows += b"\x00\x00" * HEIGHTMAP_SIZE
    write_png(path, HEIGHTMAP_SIZE, 16, bytes(rows))


def write_roadmask(path, half_x, half_z):
    span = (HEIGHTMAP_SIZE - 1) * CELL_SIZE
    rows = bytearray()
    for y in range(MASK_SIZE):
        rows.append(0)
        z = (y + 0.5) / MASK_SIZE * span - span * 0.5
        for x in range(MASK_SIZE):
            wx = (x + 0.5) / MASK_SIZE * span - span * 0.5
            inside = abs(wx) <= half_x + 1.0 and abs(z) <= half_z + 1.0
            rows.append(255 if inside else 0)
    write_png(path, MASK_SIZE, 8, bytes(rows))


def yaw_toward(frm, to):
    return math.degrees(math.atan2(to[0] - frm[0], -(to[2] - frm[2])))


def add(a, b):
    return (a[0] + b[0], a[1] + b[1], a[2] + b[2])


def scale(a, s):
    return (a[0] * s, a[1] * s, a[2] * s)


def babs(a):
    return (abs(a[0]), abs(a[1]), abs(a[2]))


class Scene:
    def __init__(self, ident, name, kind, half_x, half_z):
        self.ident = ident
        self.name = name
        self.kind = kind
        self.half_x = half_x
        self.half_z = half_z
        self.props = []
        self.spawns = []
        self.benches = []

    def prop(self, center, half, color, surface):
        self.props.append((center, half, color, surface))

    def box(self, x0, x1, z0, z1, y0, y1, color, surface):
        self.prop(((x0 + x1) * 0.5, (y0 + y1) * 0.5, (z0 + z1) * 0.5),
                  ((x1 - x0) * 0.5, (y1 - y0) * 0.5, (z1 - z0) * 0.5), color, surface)

    def both(self, x0, x1, z0, z1, y0, y1, color, surface):
        self.box(x0, x1, z0, z1, y0, y1, color, surface)
        self.box(-x1, -x0, z0, z1, y0, y1, color, surface)

    def write(self):
        folder = os.path.join(ZONES, self.ident)
        os.makedirs(folder, exist_ok=True)
        write_flat_heightmap(os.path.join(folder, "heightmap.png"))
        write_roadmask(os.path.join(folder, "roadmask.png"), self.half_x, self.half_z)
        lines = ["# generated by tools/make_arenas.py from Ghost's arena maps and test range", "",
                 "[terrain]", "heightmap = heightmap.png", "roadmask = roadmask.png",
                 "cell_size = %.1f" % CELL_SIZE, "height_offset = 0.0", "height_scale = 1.0", "",
                 "[scene]", "kind = %s" % self.kind, "name = %s" % self.name, "car = 0", "",
                 "[spawn]", "car_pos = 0.0 0.0", "car_yaw_deg = 0.0", "", "[entities]"]
        for center, half, color, surface in self.props:
            lines.append("prop = %.3f %.3f %.3f %.3f %.3f %.3f %.2f %.2f %.2f %s"
                         % (center + half + color + (surface,)))
        for i, (at, yaw) in enumerate(self.spawns):
            lines.append("spawn_point = %.3f %.3f %.3f %.1f" % (at[0], at[1], at[2], yaw))
        for at in self.benches:
            lines.append("bench = %.3f %.3f %.3f" % at)
        with open(os.path.join(folder, "zone.cfg"), "w", newline="\n") as f:
            f.write("\n".join(lines) + "\n")


def yard():
    s = Scene("yard", "the Yard", "arena", 20.0, 20.0)
    h = 20.0
    spawn_out = 16.0
    for side in (-1.0, 1.0):
        s.prop((side * (h + 0.4), 2.0, 0.0), (0.4, 2.0, h + 0.8), CONCRETE, "concrete")
        s.prop((0.0, 2.0, side * (h + 0.4)), (h + 0.8, 2.0, 0.4), CONCRETE, "concrete")
    s.prop((0.0, 1.4, 0.0), (1.6, 1.4, 1.6), DARK, "concrete")
    for side in ((-1.0, 0.0, 0.0), (1.0, 0.0, 0.0), (0.0, 0.0, -1.0), (0.0, 0.0, 1.0)):
        across = (side[2], 0.0, side[0])
        s.prop(add(scale(side, 9.0), (0.0, 0.65, 0.0)), add(add(scale(babs(across), 2.2), scale(babs(side), 0.25)), (0.0, 0.65, 0.0)),
               CONCRETE, "concrete")
        for along in (-1.0, 1.0):
            s.prop(add(add(scale(side, 12.0), scale(across, along * 6.0)), (0.0, 1.6, 0.0)), (0.5, 1.6, 0.5), DARK, "concrete")
            s.prop(add(add(scale(side, 5.0), scale(across, along * 4.5)), (0.0, 0.45, 0.0)), (0.6, 0.45, 0.6), WOOD, "wood")
        s.prop(add(scale(add(side, across), 13.0), (0.0, 1.0, 0.0)), add(add(scale(babs(side), 0.05), scale(babs(across), 1.2)), (0.0, 1.0, 0.0)),
               STEEL, "steel")
        spawn = scale(side, spawn_out)
        s.spawns.append((spawn, yaw_toward(spawn, (0.0, 0.0, 0.0))))
        s.benches.append(add(add(scale(side, spawn_out + 1.5), scale(across, 2.5)), (0.0, BENCH_TOP, 0.0)))
    return s


def alleys():
    s = Scene("alleys", "Alleys", "arena", 28.0, 22.0)
    high = 3.5
    wall = 0.4
    hx = 28.0
    hz = 22.0
    tunnel_n = -18.5
    jog_n = -15.0
    mid_s = -2.0
    mid_n = 2.0
    long_s = 15.0
    room = 20.0
    gap_out = 11.5
    gap_in = 8.5
    s.box(-hx - wall, hx + wall, hz, hz + wall, 0.0, high, CONCRETE, "concrete")
    s.box(-hx - wall, hx + wall, -hz - wall, -hz, 0.0, high, CONCRETE, "concrete")
    s.both(-hx - wall, -hx, -hz, hz, 0.0, high, CONCRETE, "concrete")
    s.both(-room, -gap_out, mid_n, long_s, 0.0, high, DARK, "concrete")
    s.box(-gap_in, gap_in, mid_n, long_s, 0.0, high, DARK, "concrete")
    s.both(-room, -gap_out, tunnel_n, mid_s, 0.0, high, DARK, "concrete")
    s.box(-gap_in, gap_in, jog_n, mid_s, 0.0, high, DARK, "concrete")
    s.box(-3.0, 3.0, -hz, tunnel_n, 0.0, high, CONCRETE, "concrete")
    s.box(-room, room, -hz, jog_n, 2.5, 2.8, CONCRETE, "concrete")
    s.box(-0.2, 0.2, mid_s, -0.7, 0.0, high, CONCRETE, "concrete")
    s.box(-0.2, 0.2, 0.7, mid_n, 0.0, high, CONCRETE, "concrete")
    s.box(-0.2, 0.2, -0.7, 0.7, 2.2, high, CONCRETE, "concrete")
    s.both(-4.2, -3.0, -1.9, -0.7, 0.0, 0.9, WOOD, "wood")
    s.both(-16.6, -15.4, 0.6, 1.8, 0.0, 0.9, WOOD, "wood")
    s.box(-0.6, 0.6, 17.6, 18.8, 0.0, high, DARK, "concrete")
    s.both(-17.25, -16.75, 16.5, 19.5, 0.0, 1.3, CONCRETE, "concrete")
    s.both(-9.6, -8.4, 15.2, 16.4, 0.0, 0.9, WOOD, "wood")
    s.both(-5.6, -4.4, 20.3, 21.5, 0.0, 0.9, WOOD, "wood")
    s.both(-13.2, -10.8, hz - 0.1, hz, 0.0, 2.0, STEEL, "steel")
    s.both(-11.3, -10.3, 13.2, 14.2, 0.0, 0.9, WOOD, "wood")
    s.both(-3.1, -3.0, -21.6, -18.9, 0.0, 2.0, STEEL, "steel")
    s.both(-21.6, -20.4, -9.0, -7.8, 0.0, 0.9, WOOD, "wood")
    for z in (8.0, 9.6):
        for side in (-1.0, 1.0):
            at = (side * 24.0, 0.0, z)
            s.spawns.append((at, yaw_toward(at, (side * 19.0, 0.0, 0.0))))
    s.benches = [(-26.6, BENCH_TOP, 4.0), (26.6, BENCH_TOP, 4.0)]
    return s


def test_range():
    s = Scene("range", "Test range", "range", 10.0, 52.0)
    table_top = 0.94
    s.prop((0.0, table_top * 0.5, 0.0), (0.45, table_top * 0.5, 0.3), WOOD, "wood")
    for i in range(6):
        z = -6.0 - i * 6.0
        s.prop((-4.0, 1.5, z), (0.3, 1.5, 0.3), CONCRETE, "concrete")
        s.prop((4.0, 1.5, z), (0.3, 1.5, 0.3), CONCRETE, "concrete")
    for i in range(4):
        z = -10.0 - i * 10.0
        x = -1.2 if i % 2 == 0 else 1.2
        s.prop((x, 1.3, z), (0.25, 0.35, 0.02), STEEL, "steel")
        s.prop((x, 0.47, z), (0.03, 0.47, 0.03), WOOD, "wood")
    s.prop((0.0, 2.0, -50.0), (8.0, 2.0, 0.5), CONCRETE, "concrete")
    for i in range(4):
        s.spawns.append(((1.2 * i, 0.0, 2.5), 0.0))
    s.benches.append((2.3, BENCH_TOP, 1.4))
    return s


if __name__ == "__main__":
    for scene in (yard(), alleys(), test_range()):
        scene.write()
        print("wrote", scene.ident, len(scene.props), "props")
